name: 'ApiGen Docs'
description: 'Simple Github Action Which Helps You To Generate PHP Code Documentation Website Using ApiGen'
author: 'varunsridharan'
branding:
  icon: 'hard-drive'
  color: 'green'
inputs:
  output_folder:
    description: 'Folder to output docs'
    default: ''
  source_folder:
    description: 'Folder to generate docs'
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/net9-oy/action-apigen:main'
  args:
    - "--working-dir"
    - ${{ inputs.working_directory }}
    - "-o"
    - ${{ inputs.output_folder }}
    - ${{ inputs.source_folder }}